spring:
  datasource:
    url: jdbc:mysql://192.168.1.124/subscription_management
    username: root
    password: subscription
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect