spring:
  datasource:
    url: jdbc:h2:mem:subscription_management
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect